### PR TITLE
Metrics-webapp: Test

### PR DESCRIPTION
**Pull request by zhorabay**
- [ ] In this branch, I:
- Created test files
- Wrote tests

### CODE REVIEW

**Comment by zhorabay** [comment]
Dear Code Reviewer,
Firstly, thank you for spending your valuable time checking my codes. I know I haven't finished my work fully yet. I still have to deploy and record a video. However, before those two actions, I wanted to be sure I did my project correctly or not. Please, review my code according to the requirements except for deployment and video recording. Thank you one more time.
P.S. I have an issue with testing CharacterList.test.js (I hope the other two tests were done correctly), what can you suggest for it?

**Comment by Alusp** [comment]
Hello @zhorabay, I have claimed your project as a Reviewer, However, Your code review limit will be counted as 1 when I review your project. Are you okay with that?

**Comment by zhorabay** [comment]
> Hello @zhorabay, I have claimed your project as a Reviewer, However, Your code review limit will be counted as 1 when I review your project. Are you okay with that?

Yes, I am, thank you @Alusp

**Review by Alusp — CHANGES_REQUESTED** [review]
Hi @zhorabay , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
  close

## Highlights

- [ ] Completed most of the tasks

## Required Changes ♻️
_Check the comments under the review._

- [x] I am requesting these changes here because you did not make enough commit for me to comment on each of your files as inline.
- [x] Good job so far, :clap: however, as part of the project requirement, you are required to give credit to the Original Designer in your acknowledgment section.
- [ ] According to the project requirement, you are supposed to record a video presentation of your project, Please resolve that. 
- [ ] According to the project requirement, you are also supposed to deploy your project and add the live demo link in your readme File.
- [x] The project requirement also says "one page with a list of items that could be filtered by some parameters; in the example below, it's a list of metrics that can be filtered by the country (imagine a search field to introduce the country name like Italy, Croatia, etc.). This page should be your homepage." Please resolve that.
- [x] The project requirement also says "When the user clicks on the "Back" button (<), the user navigates to the home page."
- [x] The link to your License in your readme file is broken please resolve it.
- woman

- [x] Please ensure that you write enough test for your project and ensure that all your test passes


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zhorabay** [comment]
Hi @Alusp 

Some requirements are still not clear to me. The point why I spent one of my limited reviews is to understand why my code doesn't match the requirements.  
- [ ] The project requirement also says "one page with a list of items that could be filtered by some parameters; in the example below, it's a list of metrics that can be filtered by the country (imagine a search field to introduce the country name like Italy, Croatia, etc.). This page should be your homepage." Please resolve that. 
- What does this requirement mean? Why my homepage doesn't match it? What did I do wrong? I divided the info into categories and fetched info for one of them. Exactly what should I change?

- [ ] The project requirement also says "When the user clicks on the "Back" button (<), the user navigates to the home page."
- Is it okay if I create the "Back" button (<) in the CharacterList page itself, not in the navigation bar?

- [ ] Please ensure that you write enough test for your project and ensure that all your test passes
- I am facing a testing issue I mentioned above in the comments. Can you suggest anything to solve it, because I don't know how to write it, please?
- The amount of the test should be the same as the amount of the components, right? So I have 3 components and 3 tests, what did I miss here?

Thank you and I ask you for one more review with details, please.

**Comment by Alusp** [comment]
Hello @zhorabay, it will be really nice if you make enough commits in your project next time, that way it will be easy for anyone reviewing your project to point out specific files in your project that need improvement. However, let me elaborate more below. ⬇️ 

- [ ] The project requirement also says "one page with a list of items that could be filtered by some parameters; in the example below, it's a list of metrics that can be filtered by the country (imagine a search field to introduce the country name like Italy, Croatia, etc.). This page should be your homepage." Please resolve that.
### ANSWER
Right now, on your homepage, only one item is clickable, which is not supposed to be, Your homepage should have a list of all the movies you are talking about, and possibly add a search bar to filter items or add a filtering mechanism and those items on your home page should be clickable and take you to a details page of the perticular item clicked.

- [ ] The project requirement also says "When the user clicks on the "Back" button (<), the user navigates to the home page."
### ANSWER
When someone clicks on the details page there should be a back arrow button showing on the details page, and when someone clicks on it, it should take the person back to the home page.

- [ ] Please ensure that you write enough test for your project and ensure that all your test passes
### ANSWER
Your Test in the test files has a small number of lines, I can see now you have increased the number of lines in the character list. please ensure that you add more tests in the remaining two files. kindly [check](https://www.digitalocean.com/community/tutorials/how-to-test-a-react-app-with-jest-and-react-testing-library) for more references on testing


### I hope this is clear enough for you. If not please let me know.

**Comment by zhorabay** [comment]
@Alusp Thank you so much!!

**Comment by Alusp** [comment]
You are most welcome. @zhorabay

**Pull request merged**
